language: java
jdk:
  - openjdk8

services:
  - mysql

branches:
  only:
    - master
cache:
  directories:
    - '$Home/.gradle'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drinkit;'
  - mysql -u root -e "CREATE USER 'jiwon'@'localhost' IDENTIFIED BY 'drinkitjiwon';"
  - mysql -u root -e "GRANT ALL ON drinkit.* TO 'jiwon'@'localhost';"

script:
  - ./gradlew clean build -Pprofile=real

before_deploy:
  - zip -r drinkit *
  - mkdir -p deploy
  - mv drinkit.zip deploy/drinkit.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: drinkit-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy  # deploy 디렉토리의 내용들만 S3로 전송
    on:
      repo: DrinKit-team-project/DrinKit-Backend
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: drinkit-bucket # S3 버킷
    key: drinkit.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: drinkit # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: drinkit-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: DrinKit-team-project/DrinKit-Backend
      branch: master

notifications:
  slack:
    rooms:
      - drinkit-members:xX1WpvUAarrwG4DlssELd083#travis
    secure: YIEmzOkbniFBiKFyfDVoutk+eZQtAyWKwG4cr9uMZScAsNn6jGAztbTQJJbjqZGi5hjakBD22jyyV4YdABPTDSYDVK9rhZi/s8DtmELcmz89FwL4voWrvFQwllod82PxfqTbmGzeY+B2R0N2831zJtvqiK2gWQvgUvM+e5tYie4YuWyQeauXl3UCEUCf+KTOqg4Vx6Vmx5Z+f/JR5/ZrxueK+ZQOSLPPFMVBH8ZNkp5rxe69ZFp7V7yxouL4BADbvCDkaLzkJ2SzshscGChOIuWg7RposWq7lPRuSl3eaSuZS6sIE7m2CA8QFA5aYlpCgTiKWN5UkkRtklT7mm0V5rDt+/1/ij2UnEV9RHaDM2C5riir8ij75bk2HHFB7S7/YrfUGE+QmL8PH6b8q+SJde7dMR2g2/kwT2O6EDCel3EISvCmw6n+oY1j7jNnhHQeNM5PIrJsOt7mAeBcnGza/opUoqyqR9GbVYtaf8xoRkndFu9ZrUdD87tqPv/0eU292wB5/+31XwKaaVA7akx/kPGhdmV6DsW75DEIDoBl4Q+oJ77f50F3Ub6zW6/vloY4XxypnnY765uFmMOUGa3THx1bY7DG/EYPI77xb6ZO9gKu6cyQCIULs3C2qYbYZlMyMMT8cKWdC2hksj8FthGSkNrR8UxOlDJbxis0G5muv/g=

