spring:
  profiles:
    active: develop # 기본 profile 선택

# develop 환경
---
spring:
  profiles: develop
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
            hibernate:
              format_sql: true

  datasource:
          username: jiwon
          password: jiwon
          url: jdbc:mysql://localhost/drinkit
          driverClassName: com.mysql.jdbc.Driver
  security:
    basic:
      enabled: false # security 기본 인증 옵션 제거

# 로그 레벨 설정
logging:
  pattern:
    level: trace

jwt:
  signingKey: drinkitjwtsecretkey

skipUrls: /social
noToSkipPath: /api/**

# 운영환경
---
spring.profiles: prod
spring.profiles.include: real-db

# 로그 레벨 설정
logging:
  pattern:
    level: info

---