spring:
 profiles:
    active: develop # 기본 profile 선택

# develop 환경
---
spring:
 profiles: develop
 jpa:
   database: mysql
   database-platform: org.hibernate.dialect.MySQL5Dialect
   show-sql: true
   hibernate:
     ddl-auto: create-drop
   properties:
    hibernate:
      format_sql: true

 datasource:
   url: jdbc:mysql://localhost/drinkit
   username: jiwon
   password: jiwon
   driver-class-name: com.mysql.jdbc.Driver

 output:
  ansi:
   enabled: ALWAYS


jwt:
  signingKey: drinkitjwtsecretkey

skipUrls: /social
noToSkipPath: /api/**

logging:
  pattern:
    level: trace

# 운영환경
---
spring.profiles: prod
spring.profiles.include: real-db

