spring:
 profiles:
    active: develop # 기본 profile 선택

# develop 환경
---
spring:
 profiles: develop
 jpa:
   database: default
   database-platform: org.hibernate.dialect.MySQL5Dialect
   show-sql: true
   hibernate:
     ddl-auto: create-drop
   properties:
    hibernate:
      format_sql: true
 output:
    ansi:
     enabled: ALWAYS

spring.developdatasource.url: jdbc:mysql://localhost/drinkit
spring.developdatasource.username: jiwon
spring.developdatasource.password: jiwon
spring.developdatasource.driver-class-name: com.mysql.jdbc.Driver




jwt:
  signingKey: drinkitjwtsecretkey

skipUrls: /social
noToSkipPath: /api/**

logging:
  pattern:
    level: trace

# 운영환경
---
spring.profiles: prod
spring.profiles.include: real-db

