POST http://localhost:8080/api/cafes/1/menus/1/reviews
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmlua2l0IiwiVVNFUk5BTUUiOiLrsLDsp4Dsm5AiLCJVU0VSX1JPTEUiOiJST0xFX1VTRVIifQ.9EX9azDidL_Tsgk5uafyStemwu1aNhFQ0Uj58jhaJdA


{"ratings" : "3.5", "contents" : "soso", "drinkImgUrl" : "/test/url"}

###