GET http://localhost:8080/api
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmlua2l0IiwiVVNFUk5BTUUiOiJKaXdvbiBCYWUiLCJVU0VSX1JPTEUiOiJST0xFX1VTRVIifQ.tXNSK6_oihbC5Nk94NQsUenkl-5yowAI5YnyYwl7RK8
###